# Generated by Django 2.0.2 on 2018-03-02 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Title')),
                ('slug', models.SlugField(max_length=90, verbose_name='Slug')),
                ('teaser_html', models.TextField(editable=False)),
                ('content_html', models.TextField(editable=False)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Updated')),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='Published')),
                ('view_count', models.IntegerField(default=0, editable=False, verbose_name='View count')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-published',),
                'get_latest_by': 'published',
            },
        ),
    ]
